#ifndef SENSOR_TYPES_H
#define SENSOR_TYPES_H

enum SensorType
{
    SENSOR_UNKNOWN,
    SENSOR_LSM6DSO32,
    SENSOR_DPS310,
    SENSOR_Bmi088Accel,
    SENSOR_Bmi088Gyro,
    SENSOR_BMP3xx,
    SENSOR_LIS2MDL,
    SENSOR_HDC302x
};

#endif
